# 1. Import Dependencie

In [4]:
!pip3 install gym[box2d] pyglet  # box2d is needed for running 2d images

  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [141 lines of output]
      Using setuptools (version 57.4.0).
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/Box2D
      copying library/Box2D/Box2D.py -> build/lib.macosx-10.9-universal2-3.10/Box2D
      copying library/Box2D/__init__.py -> build/lib.macosx-10.9-universal2-3.10/Box2D
      creating build/lib.macosx-10.9-universal2-3.10/Box2D/b2
      copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.9-universal2-3.10/Box2D/b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
      swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals

Failed to build box2d-py
  Running setup.py install for box2d-py ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for box2d-py did not run successfully.
  │ exit code: 1
  ╰─> [141 lines of output]
      Using setuptools (version 57.4.0).
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/Box2D
      copying library/Box2D/Box2D.py -> build/lib.macosx-10.9-universal2-3.10/Box2D
      copying library/Box2D/__init__.py -> build/lib.macosx-10.9-universal2-3.10/Box2D
      creating build/lib.macosx-10.9-universal2-3.10/Box2D/b2
      copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.9-universal2-3.10/Box2D/b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
      swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Glo

In [8]:
pip install gym[box2d]

  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for box2d-py: filename=box2d_py-2.3.5-cp39-cp39-macosx_10_9_x86_64.whl size=505991 sha256=0dd78949c5a8ac240c4dc15c3f15ee4edba16a32cc1cc37b68099b8f1511ad49
  Stored in directory: /Users/yoota/Library/Caches/pip/wheels/a4/c2/c1/076651c394f05fe60990cd85616c2d95bc1619aa113f559d7d
Successfully built box2d-py
Note: you may need to restart the kernel to use updated packages.


In [12]:
pip install box2d-kengz

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.4/425.4 kB 3.1 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for box2d-kengz: filename=Box2D_kengz-2.3.3-cp39-cp39-macosx_10_9_x86_64.whl size=524148 sha256=e71664b8f7f4ffc6e9c94d31d1d2339e0eac7fc3bee39c1fb51992c921cdd7d2
  Stored in directory: /Users/yoota/Library/Caches/pip/wheels/63/75/47/12244d079cfc23e87a711a1278fc666fcb73b864fc2d587092
Successfully built box2d-kengz
Note: you may need to restart the kernel to use updated packages.


In [13]:
pip install pyglet

Note: you may need to restart the kernel to use updated packages.


In [1]:
import gym
import os
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Test Environment

In [2]:
env = gym.make("CarRacing-v0")


In [4]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [5]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [7]:
env.reset()

Track generation: 1081..1356 -> 275-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1175..1483 -> 308-tiles track


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
env.render()

2022-07-11 19:58:53.125 Python[6621:189647] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/21/_7zvs2610fxgclkhl47pkcm40000gn/T/org.python.python.savedState


In [6]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))

Track generation: 1050..1321 -> 271-tiles track
Episode:1 Score:-29.629629629630028
Track generation: 1113..1399 -> 286-tiles track
Episode:2 Score:-33.33333333333379
Track generation: 1071..1343 -> 272-tiles track
Episode:3 Score:-26.199261992620254
Track generation: 1151..1443 -> 292-tiles track
Episode:4 Score:-31.27147766323068
Track generation: 970..1218 -> 248-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1164..1459 -> 295-tiles track
Episode:5 Score:-35.3741496598645
[[[102 204 102]
  [102 204 102]
  [102 229 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]

 [[102 204 102]
  [102 204 102]
  [102 229 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]

 [[102 204 102]
  [102 204 102]
  [102 229 102]
  ...
  [102 204 102]
  [102 204 102]
  [102 204 102]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [

# 3. Train Model

In [8]:
log_path = os.path.join('Training', 'Logs')

In [39]:
model = PPO("CnnPolicy", env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [40]:
model.learn(total_timesteps=400)  # running 2M timesteps might solve the problem -- will probably get to score 700

Track generation: 1190..1490 -> 300-tiles track


2022-07-11 21:27:09.201 Python[7407:225535] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/21/_7zvs2610fxgclkhl47pkcm40000gn/T/org.python.python.savedState


INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2
Logging to Training/Logs/PPO_3
Track generation: 1305..1634 -> 329-tiles track
Track generation: 1298..1627 -> 329-tiles track
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -58.3    |
| time/              |          |
|    fps             | 69       |
|    iterations      | 1        |
|    time_elapsed    | 29       |
|    total_timesteps | 2048     |
---------------------------------


# 4. Save Model

In [11]:
env = gym.make("CarRacing-v0")
env.reset()

Track generation: 1004..1259 -> 255-tiles track


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [41]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_40K_Driving_model')

In [42]:
model.save(ppo_path)

In [33]:
del model

In [9]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_428k_Driving_model_2')

In [12]:
model = PPO.load(ppo_path, env)

TypeError: argument of type 'NoneType' is not iterable

# 5. Evaluate and Test  -> if we hit 900 score, it is solved!

In [6]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1186..1486 -> 300-tiles track


2022-07-11 20:56:52.618 Python[7319:222000] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/21/_7zvs2610fxgclkhl47pkcm40000gn/T/org.python.python.savedState


Track generation: 1199..1503 -> 304-tiles track
Track generation: 954..1197 -> 243-tiles track
Track generation: 1084..1360 -> 276-tiles track
Track generation: 1267..1588 -> 321-tiles track


KeyboardInterrupt: 

In [11]:
env.close()

In [12]:
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

Track generation: 1156..1449 -> 293-tiles track


ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

In [ ]:
env.close()